## Feature Enrichment

### Historical data enrichment

Pick one client (Site, aka sender_BIC) to do the enrichment as every site will be the same process

In [2]:
site_input_dir = "/tmp/dataset/horizontal_credit_fraud_data/"
site_name = "CHASUS33_JPMorgan_Chase"

In [3]:
import os
import random
import string

import pandas as pd
history_file_name = os.path.join(site_input_dir, site_name,"history.csv" )
df_history = pd.read_csv(history_file_name)
df_history

,Time,Amount,Class,Sender_BIC,Receiver_BIC,UETR,Currency,Beneficiary_BIC,Currency_Country
0,200.0,69.99,0,CHASUS33,BARCGB22,D3NVQD93I09N3A1MTKSJKL,CHF,UBSWCHZH80A,Switzerland
1,1800.0,22.75,0,CHASUS33,CHASUS33,31GOHRXOL4KSPNUET4W63M,GBP,BARCGB22,United Kingdom
2,4200.0,32.51,0,CHASUS33,CITIUS33,DEFO36U84BOGIM1HU24ABJ,CHF,UBSWCHZH80A,Switzerland
3,5500.0,200.01,0,CHASUS33,SCBLSGSG,FPH2M8LQANN09721RATD6V,GBP,BARCGB22,United Kingdom
4,6700.0,19.85,0,CHASUS33,UBSWCHZH80A,SKF6TG6FFAH8YCSVK2SKF2,CHF,UBSWCHZH80A,Switzerland
...,...,...,...,...,...,...,...,...,...
62716,39324200.0,60.00,0,CHASUS33,SCBLSGSG,A0CBHXQJ2DG3SLI8PWWERY,AUD,ANZBAU3M,Australia
62717,39324300.0,15.49,0,CHASUS33,DEUTDEFF,NRGJ9KIFBPY3D3NSA56Z5Z,CHF,UBSWCHZH80A,Switzerland
62718,39325000.0,146.24,0,CHASUS33,UBSWCHZH80A,T5OVZIIZBOV9DAS7ZE74F1,AUD,ANZBAU3M,Australia
62719,39326300.0,136.70,0,CHASUS33,BSCHESMM,IHI9PJSDYO0W8KPEKRJ6DS,USD,CHASUS33,United States
62720,39327800.0,116.00,0,CHASUS33,BNPAFRPP,Y39K3YVFAN5RGD9CMFZMNR,GBP,BARCGB22,United Kingdom

In [4]:


history_summary = df_history.groupby('Currency').agg(
                     hist_trans_volume=('UETR', 'count'),
                     hist_total_amount=('Amount', 'sum'),
                     hist_average_amount=('Amount', 'mean')
).reset_index()

history_summary

  Currency  hist_trans_volume  hist_total_amount  hist_average_amount
0      AUD              12639         1152401.96            91.178255
1      CHF              12394         1138822.83            91.885011
2      GBP              12545         1142998.21            91.111854
3      SGD              12601         1112515.62            88.287884
4      USD              12542         1112058.46            88.666756

# Enrich Feature with Currency

In [5]:
import pandas as pd
dataset_names = ["train", "test"]
results = {}

temp_ds_df = {}
temp_resampled_df = {}


for ds_name in dataset_names:
    file_name = os.path.join(site_input_dir, site_name , f"{ds_name}.csv" )
    ds_df  = pd.read_csv(file_name)
    ds_df['Time'] = pd.to_datetime(ds_df['Time'], unit='s')

    # Set the Time column as the index
    ds_df.set_index('Time', inplace=True)
    
    resampled_df = ds_df.resample('1H').agg(
                     trans_volume=('UETR', 'count'),
                     total_amount=('Amount', 'sum'),
                     average_amount=('Amount', 'mean')
                     ).reset_index()
    
    temp_ds_df[ds_name] = ds_df
    temp_resampled_df[ds_name] = resampled_df

In [6]:
for ds_name in dataset_names:
        
    ds_df = temp_ds_df[ds_name]
    resampled_df = temp_resampled_df[ds_name]
    
    c_df = ds_df[['Currency']].resample('1H').agg({'Currency': 'first'}).reset_index()
    # Add Currency_Country to the resampled data by joining with the original DataFrame
    resampled_df2 = pd.merge(resampled_df, 
                            c_df,
                            on='Time'
                            )
    resampled_df3 = pd.merge(resampled_df2, 
                             history_summary,
                             on='Currency'
                            )
    resampled_df4 = resampled_df3.copy()
    resampled_df4['x2_y1'] = resampled_df4['average_amount']/resampled_df4['hist_trans_volume']
    
    ds_df = ds_df.sort_values('Time')
    resampled_df4 = resampled_df4.sort_values('Time')
    merged_df = pd.merge_asof(ds_df, resampled_df4, on='Time' )
    
    merged_df = merged_df.drop(columns=['Currency_y']).rename(columns={'Currency_x': 'Currency'})

    
    results[ds_name] = merged_df
    
    
    

print(results)

{'train':                      Time  Class  Amount Sender_BIC Receiver_BIC  \
0     1971-04-01 04:28:20      0   92.12   CHASUS33     CITIUS33
1     1971-04-01 04:35:00      0    1.99   CHASUS33     HSBCHKHH
2     1971-04-01 04:35:00      0  399.99   CHASUS33     BSCHESMM
3     1971-04-01 04:38:20      0    1.50   CHASUS33     SCBLSGSG
4     1971-04-01 04:53:20      0    2.99   CHASUS33     BNPAFRPP
...                   ...    ...     ...        ...          ...
39977 1972-03-10 21:53:20      0    4.45   CHASUS33     CHASUS33
39978 1972-03-10 22:11:40      0  124.99   CHASUS33     SCBLSGSG
39979 1972-03-10 22:26:40      0    1.79   CHASUS33     HSBCHKHH
39980 1972-03-10 22:36:40      0   20.32   CHASUS33     HSBCHKHH
39981 1972-03-10 22:50:00      0    5.49   CHASUS33     CITIUS33

                         UETR Currency Beneficiary_BIC Currency_Country  \
0      83NRFFS7OCIOBKR984EP8J      USD        CITIUS33    United States
1      QPZRQG1DIOUJH1BKG7FXWT      GBP        BARCGB22   United Kingdom
2      Z2WHNMP5BMOTFC7H3TGZTD      AUD        ANZBAU3M        Australia
3      27TVIU6FDLQC0A85D4CONT      SGD        SCBLSGSG        Singapore
4      DTPQASCVSGYE9ZLKBD7E0Y      GBP        BARCGB22   United Kingdom
...                       ...      ...             ...              ...
39977  8WBA8761P1C5QHI1O35J1O      AUD        ANZBAU3M        Australia
39978  MNX4G5X324XGJWQIK0IH0J      CHF     UBSWCHZH80A      Switzerland
39979  TPS56Q8EMPM805A0E65POO      AUD        ANZBAU3M        Australia
39980  UDXNS4DLH42JDHIGZ5WI2H      AUD        ANZBAU3M        Australia
39981  QDPO5A9G1593XT6KVMBV3E      GBP        BARCGB22   United Kingdom

       trans_volume  total_amount  average_amount  hist_trans_volume  \
0                 6        632.08      105.346667              12542
1                 6        632.08      105.346667              12542
2                 6        632.08      105.346667              12542
3                 6        632.08      105.346667              12542
4                 6        632.08      105.346667              12542
...             ...           ...             ...                ...
39977             6        758.04      126.340000              12394
39978             4        152.59       38.147500              12394
39979             4        152.59       38.147500              12394
39980             4        152.59       38.147500              12394
39981             4        152.59       38.147500              12394

       hist_total_amount  hist_average_amount     x2_y1
0             1112058.46            88.666756  0.008400
1             1112058.46            88.666756  0.008400
2             1112058.46            88.666756  0.008400
3             1112058.46            88.666756  0.008400
4             1112058.46            88.666756  0.008400
...                  ...                  ...       ...
39977         1138822.83            91.885011  0.010194
39978         1138822.83            91.885011  0.003078
39979         1138822.83            91.885011  0.003078
39980         1138822.83            91.885011  0.003078
39981         1138822.83            91.885011  0.003078

[39982 rows x 16 columns], 'test':                      Time  Class  Amount Sender_BIC Receiver_BIC  \
0     1971-04-01 04:26:40      0    4.62   CHASUS33     DEUTDEFF
1     1971-04-01 05:15:00      0  100.16   CHASUS33     BARCGB22
2     1971-04-01 05:15:00      0   28.88   CHASUS33     DEUTDEFF
3     1971-04-01 05:28:20      0   76.59   CHASUS33     BSCHESMM
4     1971-04-01 05:35:00      0   30.00   CHASUS33  UBSWCHZH80A
...                   ...    ...     ...        ...          ...
11315 1972-03-10 17:55:00      0    2.00   CHASUS33     CITIUS33
11316 1972-03-10 19:26:40      0   91.20   CHASUS33     ANZBAU3M
11317 1972-03-10 20:26:40      0    2.32   CHASUS33  UBSWCHZH80A
11318 1972-03-10 20:40:00      0   58.42   CHASUS33     BNPAFRPP
11319 1972-03-10 20:40:00      0  787.95   CHASUS33     BARCGB22

                         UETR Currency Beneficiary_BIC Currency_Country  \
0      FLJHS130C18YZ3LP33H0AY      CHF     UBSWCHZH80A      Switzerland
1      F995XCQNUCKCR8KDIXD1NH      CHF     UBSWCHZH80A      Switzerland
2      HAKMKXONAWZVRYTLF4BK3D      GBP        BARCGB22   United Kingdom
3      NYLPN7OQNBZ6ZIFPFCY7GR      CHF     UBSWCHZH80A      Switzerland
4      18Q5AN49KN1033YDGXE5FQ      CHF     UBSWCHZH80A      Switzerland
...                       ...      ...             ...              ...
11315  2A30MFXN4GKYHXTLQXQWRR      CHF     UBSWCHZH80A      Switzerland
11316  ORTJ091NQUPCSDJ96RRC8N      CHF     UBSWCHZH80A      Switzerland
11317  4JZRQCWX69SKG06A541C5I      CHF     UBSWCHZH80A      Switzerland
11318  8C9N2EJ6KETCGLIBGB9QV8      GBP        BARCGB22   United Kingdom
11319  THZ3B3LDIKHTM4GZC371V5      USD        CHASUS33    United States

       trans_volume  total_amount  average_amount  hist_trans_volume  \
0                 1          4.62        4.620000              12394
1                 5        496.69       99.338000              12394
2                 5        496.69       99.338000              12394
3                 5        496.69       99.338000              12394
4                 5        496.69       99.338000              12394
...             ...           ...             ...                ...
11315             2          2.85        1.425000              12394
11316             1         91.20       91.200000              12394
11317             3        848.69      282.896667              12394
11318             3        848.69      282.896667              12394
11319             3        848.69      282.896667              12394

       hist_total_amount  hist_average_amount     x2_y1
0             1138822.83            91.885011  0.000373
1             1138822.83            91.885011  0.008015
2             1138822.83            91.885011  0.008015
3             1138822.83            91.885011  0.008015
4             1138822.83            91.885011  0.008015
...                  ...                  ...       ...
11315         1138822.83            91.885011  0.000115
11316         1138822.83            91.885011  0.007358
11317         1138822.83            91.885011  0.022825
11318         1138822.83            91.885011  0.022825
11319         1138822.83            91.885011  0.022825

[11320 rows x 16 columns]}

# Enrich feature for beneficiary country

In [7]:

history_summary2 = df_history.groupby('Beneficiary_BIC').agg(
                     hist_trans_volume=('UETR', 'count'),
                     hist_total_amount=('Amount', 'sum'),
                     hist_average_amount=('Amount', 'mean')
).reset_index()

history_summary2

  Beneficiary_BIC  hist_trans_volume  hist_total_amount  hist_average_amount
0        ANZBAU3M              12639         1152401.96            91.178255
1        BARCGB22              12545         1142998.21            91.111854
2        CHASUS33               6319          542192.38            85.803510
3        CITIUS33               6223          569866.08            91.574173
4        SCBLSGSG              12601         1112515.62            88.287884
5     UBSWCHZH80A              12394         1138822.83            91.885011

In [8]:
import pandas as pd
dataset_names = ["train", "test"]
results2 = {}
for ds_name in dataset_names:
    ds_df = temp_ds_df[ds_name]
    resampled_df = temp_resampled_df[ds_name]
    
    c_df = ds_df[['Beneficiary_BIC']].resample('1H').agg({'Beneficiary_BIC': 'first'}).reset_index()
    
    # Add Beneficiary_BIC to the resampled data by joining with the original DataFrame
    resampled_df2 = pd.merge(resampled_df, 
                            c_df,
                            on='Time'
                            )
    
    resampled_df3 = pd.merge(resampled_df2, 
                             history_summary2,
                             on='Beneficiary_BIC'
                            )
    
    
    resampled_df4 = resampled_df3.copy()
    resampled_df4['x3_y2'] = resampled_df4['average_amount']/resampled_df4['hist_trans_volume']
   
    ds_df = ds_df.sort_values('Time')
    resampled_df4 = resampled_df4.sort_values('Time')

    merged_df2 = pd.merge_asof(ds_df, resampled_df4, on='Time' )
    merged_df2 = merged_df2.drop(columns=['Beneficiary_BIC_y']).rename(columns={'Beneficiary_BIC_x': 'Beneficiary_BIC'})
    
    
    results2[ds_name] = merged_df2

print(results2)

{'train':                      Time  Class  Amount Sender_BIC Receiver_BIC  \
0     1971-04-01 04:28:20      0   92.12   CHASUS33     CITIUS33
1     1971-04-01 04:35:00      0    1.99   CHASUS33     HSBCHKHH
2     1971-04-01 04:35:00      0  399.99   CHASUS33     BSCHESMM
3     1971-04-01 04:38:20      0    1.50   CHASUS33     SCBLSGSG
4     1971-04-01 04:53:20      0    2.99   CHASUS33     BNPAFRPP
...                   ...    ...     ...        ...          ...
39977 1972-03-10 21:53:20      0    4.45   CHASUS33     CHASUS33
39978 1972-03-10 22:11:40      0  124.99   CHASUS33     SCBLSGSG
39979 1972-03-10 22:26:40      0    1.79   CHASUS33     HSBCHKHH
39980 1972-03-10 22:36:40      0   20.32   CHASUS33     HSBCHKHH
39981 1972-03-10 22:50:00      0    5.49   CHASUS33     CITIUS33

                         UETR Currency Beneficiary_BIC Currency_Country  \
0      83NRFFS7OCIOBKR984EP8J      USD        CITIUS33    United States
1      QPZRQG1DIOUJH1BKG7FXWT      GBP        BARCGB22   United Kingdom
2      Z2WHNMP5BMOTFC7H3TGZTD      AUD        ANZBAU3M        Australia
3      27TVIU6FDLQC0A85D4CONT      SGD        SCBLSGSG        Singapore
4      DTPQASCVSGYE9ZLKBD7E0Y      GBP        BARCGB22   United Kingdom
...                       ...      ...             ...              ...
39977  8WBA8761P1C5QHI1O35J1O      AUD        ANZBAU3M        Australia
39978  MNX4G5X324XGJWQIK0IH0J      CHF     UBSWCHZH80A      Switzerland
39979  TPS56Q8EMPM805A0E65POO      AUD        ANZBAU3M        Australia
39980  UDXNS4DLH42JDHIGZ5WI2H      AUD        ANZBAU3M        Australia
39981  QDPO5A9G1593XT6KVMBV3E      GBP        BARCGB22   United Kingdom

       trans_volume  total_amount  average_amount  hist_trans_volume  \
0                 6        632.08      105.346667               6223
1                 6        632.08      105.346667               6223
2                 6        632.08      105.346667               6223
3                 6        632.08      105.346667               6223
4                 6        632.08      105.346667               6223
...             ...           ...             ...                ...
39977             6        758.04      126.340000              12394
39978             4        152.59       38.147500              12394
39979             4        152.59       38.147500              12394
39980             4        152.59       38.147500              12394
39981             4        152.59       38.147500              12394

       hist_total_amount  hist_average_amount     x3_y2
0              569866.08            91.574173  0.016929
1              569866.08            91.574173  0.016929
2              569866.08            91.574173  0.016929
3              569866.08            91.574173  0.016929
4              569866.08            91.574173  0.016929
...                  ...                  ...       ...
39977         1138822.83            91.885011  0.010194
39978         1138822.83            91.885011  0.003078
39979         1138822.83            91.885011  0.003078
39980         1138822.83            91.885011  0.003078
39981         1138822.83            91.885011  0.003078

[39982 rows x 16 columns], 'test':                      Time  Class  Amount Sender_BIC Receiver_BIC  \
0     1971-04-01 04:26:40      0    4.62   CHASUS33     DEUTDEFF
1     1971-04-01 05:15:00      0  100.16   CHASUS33     BARCGB22
2     1971-04-01 05:15:00      0   28.88   CHASUS33     DEUTDEFF
3     1971-04-01 05:28:20      0   76.59   CHASUS33     BSCHESMM
4     1971-04-01 05:35:00      0   30.00   CHASUS33  UBSWCHZH80A
...                   ...    ...     ...        ...          ...
11315 1972-03-10 17:55:00      0    2.00   CHASUS33     CITIUS33
11316 1972-03-10 19:26:40      0   91.20   CHASUS33     ANZBAU3M
11317 1972-03-10 20:26:40      0    2.32   CHASUS33  UBSWCHZH80A
11318 1972-03-10 20:40:00      0   58.42   CHASUS33     BNPAFRPP
11319 1972-03-10 20:40:00      0  787.95   CHASUS33     BARCGB22

                         UETR Currency Beneficiary_BIC Currency_Country  \
0      FLJHS130C18YZ3LP33H0AY      CHF     UBSWCHZH80A      Switzerland
1      F995XCQNUCKCR8KDIXD1NH      CHF     UBSWCHZH80A      Switzerland
2      HAKMKXONAWZVRYTLF4BK3D      GBP        BARCGB22   United Kingdom
3      NYLPN7OQNBZ6ZIFPFCY7GR      CHF     UBSWCHZH80A      Switzerland
4      18Q5AN49KN1033YDGXE5FQ      CHF     UBSWCHZH80A      Switzerland
...                       ...      ...             ...              ...
11315  2A30MFXN4GKYHXTLQXQWRR      CHF     UBSWCHZH80A      Switzerland
11316  ORTJ091NQUPCSDJ96RRC8N      CHF     UBSWCHZH80A      Switzerland
11317  4JZRQCWX69SKG06A541C5I      CHF     UBSWCHZH80A      Switzerland
11318  8C9N2EJ6KETCGLIBGB9QV8      GBP        BARCGB22   United Kingdom
11319  THZ3B3LDIKHTM4GZC371V5      USD        CHASUS33    United States

       trans_volume  total_amount  average_amount  hist_trans_volume  \
0                 1          4.62        4.620000              12394
1                 5        496.69       99.338000              12394
2                 5        496.69       99.338000              12394
3                 5        496.69       99.338000              12394
4                 5        496.69       99.338000              12394
...             ...           ...             ...                ...
11315             2          2.85        1.425000              12394
11316             1         91.20       91.200000              12394
11317             3        848.69      282.896667              12394
11318             3        848.69      282.896667              12394
11319             3        848.69      282.896667              12394

       hist_total_amount  hist_average_amount     x3_y2
0             1138822.83            91.885011  0.000373
1             1138822.83            91.885011  0.008015
2             1138822.83            91.885011  0.008015
3             1138822.83            91.885011  0.008015
4             1138822.83            91.885011  0.008015
...                  ...                  ...       ...
11315         1138822.83            91.885011  0.000115
11316         1138822.83            91.885011  0.007358
11317         1138822.83            91.885011  0.022825
11318         1138822.83            91.885011  0.022825
11319         1138822.83            91.885011  0.022825

[11320 rows x 16 columns]}

In [10]:
final_results = {}
for name in results:
    df = results[name]
    df2 = results2[name]
    df3 = df2[["Time", "Beneficiary_BIC", "x3_y2"]].copy()
    df4 = pd.merge(df, df3, on=['Time', 'Beneficiary_BIC'])
    final_results[name] = df4

    
for name in final_results:
    site_dir = os.path.join(site_input_dir, site_name)
    os.makedirs(site_dir, exist_ok=True)
    enrich_file_name = os.path.join(site_dir, f"{name}_enrichment.csv")
    print(enrich_file_name)
    final_results[name].to_csv(enrich_file_name) 
    
final_results["train"]

/tmp/dataset/horizontal_credit_fraud_data/CHASUS33_JPMorgan_Chase/train_enrichment.csv
/tmp/dataset/horizontal_credit_fraud_data/CHASUS33_JPMorgan_Chase/test_enrichment.csv

,Time,Class,Amount,Sender_BIC,Receiver_BIC,UETR,Currency,Beneficiary_BIC,Currency_Country,trans_volume,total_amount,average_amount,hist_trans_volume,hist_total_amount,hist_average_amount,x2_y1,x3_y2
0,1971-04-01 04:28:20,0,92.12,CHASUS33,CITIUS33,83NRFFS7OCIOBKR984EP8J,USD,CITIUS33,United States,6,632.08,105.346667,12542,1112058.46,88.666756,0.008400,0.016929
1,1971-04-01 04:35:00,0,1.99,CHASUS33,HSBCHKHH,QPZRQG1DIOUJH1BKG7FXWT,GBP,BARCGB22,United Kingdom,6,632.08,105.346667,12542,1112058.46,88.666756,0.008400,0.016929
2,1971-04-01 04:35:00,0,399.99,CHASUS33,BSCHESMM,Z2WHNMP5BMOTFC7H3TGZTD,AUD,ANZBAU3M,Australia,6,632.08,105.346667,12542,1112058.46,88.666756,0.008400,0.016929
3,1971-04-01 04:38:20,0,1.50,CHASUS33,SCBLSGSG,27TVIU6FDLQC0A85D4CONT,SGD,SCBLSGSG,Singapore,6,632.08,105.346667,12542,1112058.46,88.666756,0.008400,0.016929
4,1971-04-01 04:53:20,0,2.99,CHASUS33,BNPAFRPP,DTPQASCVSGYE9ZLKBD7E0Y,GBP,BARCGB22,United Kingdom,6,632.08,105.346667,12542,1112058.46,88.666756,0.008400,0.016929
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41161,1972-03-10 21:53:20,0,4.45,CHASUS33,CHASUS33,8WBA8761P1C5QHI1O35J1O,AUD,ANZBAU3M,Australia,6,758.04,126.340000,12394,1138822.83,91.885011,0.010194,0.010194
41162,1972-03-10 22:11:40,0,124.99,CHASUS33,SCBLSGSG,MNX4G5X324XGJWQIK0IH0J,CHF,UBSWCHZH80A,Switzerland,4,152.59,38.147500,12394,1138822.83,91.885011,0.003078,0.003078
41163,1972-03-10 22:26:40,0,1.79,CHASUS33,HSBCHKHH,TPS56Q8EMPM805A0E65POO,AUD,ANZBAU3M,Australia,4,152.59,38.147500,12394,1138822.83,91.885011,0.003078,0.003078
41164,1972-03-10 22:36:40,0,20.32,CHASUS33,HSBCHKHH,UDXNS4DLH42JDHIGZ5WI2H,AUD,ANZBAU3M,Australia,4,152.59,38.147500,12394,1138822.83,91.885011,0.003078,0.003078
41165,1972-03-10 22:50:00,0,5.49,CHASUS33,CITIUS33,QDPO5A9G1593XT6KVMBV3E,GBP,BARCGB22,United Kingdom,4,152.59,38.147500,12394,1138822.83,91.885011,0.003078,0.003078

In [10]:
! tree {site_input_dir}

/tmp/dataset/horizontal_credit_fraud_data/
├── ANZBAU3M_ANZ_Bank
│   ├── history.csv
│   ├── test.csv
│   └── train.csv
├── BARCGB22_Barclays_Bank
│   ├── history.csv
│   ├── test.csv
│   └── train.csv
├── BNPAFRPP_BNP_Paribas
│   ├── history.csv
│   ├── test.csv
│   └── train.csv
├── BSCHESMM_Banco_Santander
│   ├── history.csv
│   ├── test.csv
│   └── train.csv
├── CHASUS33_JPMorgan_Chase
│   ├── history.csv
│   ├── test.csv
│   ├── test_enrichment.csv
│   ├── train.csv
│   └── train_enrichment.csv
├── CITIUS33_Citibank
│   ├── history.csv
│   ├── test.csv
│   └── train.csv
├── DEUTDEFF_Deutsche_Bank
│   ├── history.csv
│   ├── test.csv
│   └── train.csv
├── history.csv
├── HSBCHKHH_HSBC
│   ├── history.csv
│   ├── test.csv
│   └── train.csv
├── SCBLSGSG_Standard_Chartered_Bank
│   ├── history.csv
│   ├── test.csv
│   └── train.csv
├── test.csv
├── train.csv
└── UBSWCHZH80A_UBS
    ├── history.csv
    ├── test.csv
    └── train.csv

10 directories, 35 files

In [11]:
ls -al  /tmp/dataset/horizontal_credit_fraud_data/CHASUS33_JPMorgan_Chase/

total 9776
drwxrwxr-x  2 chester chester    4096 Jul 29 08:31 ./
drwxrwxr-x 12 chester chester    4096 Jul 29 08:31 ../
-rw-rw-r--  1 chester chester 5343086 Jul 29 08:31 history.csv
-rw-rw-r--  1 chester chester  977888 Jul 29 08:31 test.csv
-rw-rw-r--  1 chester chester   58854 Jul 29 08:31 test_enrichment.csv
-rw-rw-r--  1 chester chester 3409228 Jul 29 08:31 train.csv
-rw-rw-r--  1 chester chester  203260 Jul 29 08:31 train_enrichment.csv

In [12]:
! find /tmp/dataset/horizontal_credit_fraud_data/CHASUS33_JPMorgan_Chase/ -exec wc -l {} \;

wc: /tmp/dataset/horizontal_credit_fraud_data/CHASUS33_JPMorgan_Chase/: Is a directory
0 /tmp/dataset/horizontal_credit_fraud_data/CHASUS33_JPMorgan_Chase/
39838 /tmp/dataset/horizontal_credit_fraud_data/CHASUS33_JPMorgan_Chase/train.csv
300 /tmp/dataset/horizontal_credit_fraud_data/CHASUS33_JPMorgan_Chase/test_enrichment.csv
1012 /tmp/dataset/horizontal_credit_fraud_data/CHASUS33_JPMorgan_Chase/train_enrichment.csv
11426 /tmp/dataset/horizontal_credit_fraud_data/CHASUS33_JPMorgan_Chase/test.csv
62610 /tmp/dataset/horizontal_credit_fraud_data/CHASUS33_JPMorgan_Chase/history.csv

Let's go back to the [XGBoost Notebook](./xgboost.ipynb)